# Generated by Django 2.2.2 on 2020-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pno',
            field=models.CharField(max_length=11),
        ),
    ]
