# Generated by Django 2.2.2 on 2020-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200331_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MRP',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
