# Generated by Django 4.1 on 2022-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_servicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servicedate',
            field=models.DateField(auto_now=True),
        ),
    ]
